package:
  name: microscope_image_converter
  version: '0.0.1'

source:
  git_url: https://github.com/shahcompbio/microscope_image_converter.git
  git_rev: v0.0.1

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python

about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for converting images'

